# Generated by Django 5.0 on 2023-12-20 14:12

import badge.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('image1', models.ImageField(upload_to=badge.models.image_upload_path)),
                ('image2', models.ImageField(upload_to=badge.models.image_upload_path)),
            ],
        ),
    ]
