# Generated by Django 5.0 on 2023-12-20 03:05

import badge.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='image',
            field=models.ImageField(upload_to=badge.models.image_upload_path),
        ),
    ]
