# Generated by Django 5.0 on 2023-12-20 05:58

import django.db.models.deletion
import fishbread.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('charity', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FishbreadType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('image1', models.ImageField(upload_to=fishbread.models.image_upload_path)),
                ('image2', models.ImageField(upload_to=fishbread.models.image_upload_path)),
                ('image3', models.ImageField(upload_to=fishbread.models.image_upload_path)),
            ],
        ),
        migrations.CreateModel(
            name='Fishbread',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.IntegerField(default=0)),
                ('start_day', models.DateField(auto_now_add=True)),
                ('end_day', models.DateField()),
                ('isDonated', models.BooleanField(default=False)),
                ('charity', models.ManyToManyField(blank=True, to='charity.charity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fishbreads', to=settings.AUTH_USER_MODEL)),
                ('fishbreadtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fishbread', to='fishbread.fishbreadtype')),
            ],
        ),
    ]
