# Generated by Django 5.0 on 2023-12-20 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishbread', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fishbread',
            name='end_day',
            field=models.DateField(null=True),
        ),
    ]
